---
repository: sproogen/resume-theme
favicon: images/profile.png
url: "https://jake-huen.github.io/"
title: 평생 성장하고 싶은 개발자
locale : "ko-KR"
version: 2

name: 김태헌
email: taehuen7757@gmail.com

darkmode: true

github_username:  Jake-huen
instagram_username: tt_honeyee
additional_links:
  - title: tistory blog
    icon: "fab blogger"
    url: https://jobdong7757.tistory.com/
about_profile_image: images/jake-huen.jpeg
about_content: |
  안녕하세요 주니어 백엔드 개발자 김태헌입니다. 
  
  같이 일하고 싶어하는 개발자가 되고 싶습니다.
  
  Spring 백엔드 개발과 데브옵스에 대해 관심이 많습니다.
  
  저는 항상 새로운 기술에 대한 열정이 있으며, 할아버지가 되어서도 성장하고 싶습니다.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: 자동 배포 서비스 - Kuploy
        link: https://github.com/K-luster/KlusterWeb
        sub_title: 졸업프로젝트
        additional_links:
          - title: Kuploy 웹 서비스 링크
            url: http://kluster.iptime.org:9000/
        caption: 2023.03 ~ 2023.11
        description: |
          건국대학교 학생들을 위해 CI/CD 과정을 자동화하여 편리하게 빌드 및 배포를 도와주는 웹 서비스. <br>
          CI, CD를 모르는 사용자는 배포 파일만 업로드하면 클러스터링 된 컴퓨터에서 배포를 도와줌.<br>
          Docker-Compose를 작성한 사용자는 Docker-compose와 Dockerfile만 업로드하면 클러스터링 된 컴퓨터에서 배포를 도와줌.<br>
          주요기능: 클러스터링, CI/CD, 모니터링 및 웹 서비스. <br>
          기술스택: <mark>Svelte</mark>, <mark>Spring boot</mark>, <mark>ArgoCD</mark>, <mark>GithubAction</mark>, <mark>Kubernetes</mark> <br>
          <mark>Docker</mark>, <mark>Docker-compsoe</mark>

      - title: MZTI - MBTI 과몰입 방지 서비스
        layout: list
        link: https://github.com/TEAMMZC/MZTI
        sub_title: 건국대학교 해커톤 오케스트라 - 우수상
        caption: 2023.08 ~ 2023.08
        description: |
          MBTI에 과몰입하는 MZ 세대를 위해, 나와 다른 MBTI를 이해할 수 있도록 도와주는 프로젝트. <br>
          주요기능: MBTI 유형 비교, MBTI 학습, 프로필 및 회원정보, 로그인, 회원가입. <br>
          기술스택: <mark>AOS</mark>, <mark>Spring boot</mark>, <mark>AWS EC2</mark>, <mark>AWS S3</mark>, <mark>Docker</mark>

      - title: 모여타 - 택시팟 매칭 서비스
        layout: list
        link: https://github.com/TeamFighting
        caption: 2023.08 ~ 2023.11
        description: |
          주요기능 : 실명 인증 및 학교 인증을 통한 신원 확인이 가능합니다. 동승자 간의 거리 별 더치페이를 제공합니다. 합승을 통해 절약한 총 택시비 조회 서비스를 제공합니다.

  - title: Education
    layout: list
    content:
      - layout: left
        title: 건국대학교
        link: https://www.konkuk.ac.kr
        caption: 2018.03 ~ 2023.12
        sub_title: 건국대학교 컴퓨터공학과
        description: |
          건국대학교 컴퓨터공학과 수업에서 79학점의 전공학점을 취득하였습니다.

  - title: 블로그
    layout: list
    content:
      - layout: left
        title: 개발 블로그
        link: https://jobdong7757.tistory.com/
        caption: 2019.08 ~ present
        description: |
          기록하며 성장을 도모하는 것을 좋아합니다. 꾸준히 개발에 대한 시행착오와 경험을 기록중입니다.

footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

# Style and layout modifications
scss: |
  // Modify the style and layout here
  body {
    background-color: #f0f0f0;
    font-family: Arial, sans-serif;
  }

  .page-content {
    background-color: #fff;
    box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.1);
    border-radius: 10px;
    margin: 20px;
    padding: 20px;
  }

  .project-item {
    border: 1px solid #ddd;
    border-radius: 5px;
    margin-bottom: 20px;
    padding: 20px;
  }

  .project-title {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin-bottom: 20px;
  }

  .project-subtitle {
    font-size: 18px;
    font-weight: bold;
    color: #555;
    margin-top: 10px;
  }

  .project-caption {
    font-size: 14px;
    color: #888;
    margin-top: 10px;
  }

  .project-description {
    font-size: 16px;
    color: #333;
    margin-top: 10px;
    line-height: 1.4;
  }

  .project-icon {
    margin-right: 10px;
    font-size: 18px;
    color: #007bff;
  }

  .project-mark {
    background-color: #f0f0f0;
    padding: 3px 6px;
    border-radius: 3px;
    font-weight: bold;
  }
